version: "3.8"

services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks: 
            - learn-tdd
    
    nginx:
        image: nginx:alpine
        ports: 
            - "8989:80"
        volumes: 
            - ./:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks: 
            - learn-tdd

networks: 
    learn-tdd:
        driver: bridge          